/**
* Class Name         : Ev_PricingCondition_Service
* Developer          : D Sridhar           
* Created Date       : 13-03-2024
* @description       : This JS handles contains all the additional data and functions required by the main JS
* Last Modified Date : 13-03-2024
*/
export const categoryOptions = {
    "RL Commission Basis": { "fieldName": "ZRLC__c", "category": "Commission" },
    "Rockwell Commission": { "fieldName": "ZRC__c", "category": "Commission" },
    "WEU Commission": { "fieldName": "ZCWE__c", "category": "Commission" },
    "Customer Rebates": { "fieldName": "ZREB__c", "category": "Discount" },
    "Disc-Contract Qty": { "fieldName": "ZDIS__c", "category": "Discount" },
    "Disc-Pay In Adv %": { "fieldName": "ZDAJ__c", "category": "Discount" },
    "Disc-Pay In Adv Qty": { "fieldName": "ZPCT__c", "category": "Discount" },
    "Disc-Promotion %": { "fieldName": "ZDPR__c", "category": "Discount" },
    "Discount-Special": { "fieldName": "ZPRO__c", "category": "Discount" },
    "Admin Fee / Ton": { "fieldName": "ZADN__c", "category": "Fees" },
    "Admin Flat Fee": { "fieldName": "ZAD__c", "category": "Fees" },
    "Handling Flat Fee": { "fieldName": "ZF11__c", "category": "Fees" },
    "Service Fee Flat": { "fieldName": "ZSFF__c", "category": "Fees" },
    "Service Fee Quantity": { "fieldName": "ZSFT__c", "category": "Fees" },
    "Bagged Freight": { "fieldName": "ZF01__c", "category": "Freight" },
    "Barge Freight / Ton": { "fieldName": "ZF2__c", "category": "Freight" },
    "Dedicated frt rebill": { "fieldName": "ZDFR__c", "category": "Freight" },
    "Extra freight rebill": { "fieldName": "ZMF2__c", "category": "Freight" },
    "Leased Railcar/Ton": { "fieldName": "ZLRT__c", "category": "Freight" },
    "Misc  Freight Flat": { "fieldName": "ZF6__c", "category": "Freight" },
    "Rail Fr. Flat Fee": { "fieldName": "ZF9__c", "category": "Freight" },
    "Rail Freight / Ton": { "fieldName": "ZF3__c", "category": "Freight" },
    "Shortfall Price/Ton": { "fieldName": "ZSPA__c", "category": "Freight" },
    "Truck Fr. Flat Fee": { "fieldName": "ZF7__c", "category": "Freight" },
    "Truck Fr. Flat fee": { "fieldName": "ZF7__c", "category": "Freight" },
    "Truck Freight / Ton": { "fieldName": "ZF1__c", "category": "Freight" },
    "Truck Freight/Ton": { "fieldName": "ZF1__c", "category": "Freight" },
    "Truck Freight Flat": { "fieldName": "ZMF7__c", "category": "Freight" },
    "Vessel Freight / Ton": { "fieldName": "ZF16__c", "category": "Freight" },
    "Harbor Maintenance": { "fieldName": "ZF22__c", "category": "Misc" },
    "Logistics Srv / Ton": { "fieldName": "ZMF6__c", "category": "Misc" },
    "Pallet Charges": { "fieldName": "ZPLT__c", "category": "Misc" },
    "Terminal Fee / Ton": { "fieldName": "ZF4__c", "category": "Misc" },
    "Cust material price": { "fieldName": "ZCPR__c", "category": "Product" },
    "Material Flat Rate": { "fieldName": "ZCPF__c", "category": "Product" },
    "Alabama SeveranceTax": { "fieldName": "ZAST__c", "category": "Surcharges" },
    "CO2 Surcharge": { "fieldName": "ZCO2__c", "category": "Surcharges" },
    "Fuel SurCh Rail/MB": { "fieldName": "ZSRM__c", "category": "Surcharges" },
    "Fuel SurCh Rail/Mile": { "fieldName": "ZRMI__c", "category": "Surcharges" },
    "Fuel SurCh Rail/Ton": { "fieldName": "ZSRT__c", "category": "Surcharges" },
    "Fuel SurChTruck /Ton": { "fieldName": "ZSTT__c", "category": "Surcharges" },
    "Fuel SurChTruck Flat": { "fieldName": "ZSTF__c", "category": "Surcharges" },
    "FuelSurCh Vessel/Ton": { "fieldName": "ZSVF__c", "category": "Surcharges" },
    "Misc  Surcharge /Ton": { "fieldName": "ZMIS__c", "category": "Surcharges" },
    "Misc Fuel Surcharge": { "fieldName": "ZMFS__c", "category": "Surcharges" },
    "Spread Chrg / Ton": { "fieldName": "ZF31__c", "category": "Surcharges" },
    "Var F.Surch Truck": { "fieldName": "ZVFS__c", "category": "Surcharges" }
};

/* Not Using as of 15-04-2024 */
/*
export const pcaDataMap = {
    "ZAD": { "salesOrg": "2201", "cXRanking": "5", "cXPriceCategory": "Fees", "Description": "Admin Flat Fee" },
    "ZADN": { "salesOrg": "2201", "cXRanking": "5", "cXPriceCategory": "Fees", "Description": "Admin Fee / Ton" },
    "ZAST": { "salesOrg": "2203", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "Alabama SeveranceTax" },
    "ZCO2": { "salesOrg": "2201", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "CO2 Surcharge" },
    "ZCPF": { "salesOrg": "CZ45", "cXRanking": "1", "cXPriceCategory": "Product", "Description": "Material Flat Rate" },
    "ZCPR": { "salesOrg": "2201", "cXRanking": "1", "cXPriceCategory": "Product", "Description": "Cust material price" },
    "ZCWE": { "salesOrg": "BE03", "cXRanking": "6", "cXPriceCategory": "Commission", "Description": "WEU Commission" },
    "ZDAJ": { "salesOrg": "BA02", "cXRanking": "4", "cXPriceCategory": "Discount", "Description": "Disc-Pay In Adv %" },
    "ZDFR": { "salesOrg": "2213", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Dedicated frt rebill" },
    "ZDIS": { "salesOrg": "BA02", "cXRanking": "4", "cXPriceCategory": "Discount", "Description": "Disc-Contract Qty" },
    "ZDPR": { "salesOrg": "BA02", "cXRanking": "4", "cXPriceCategory": "Discount", "Description": "Disc-Promotion %" },
    "ZF01": { "salesOrg": "BE03", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Bagged Freight" },
    "ZF1": { "salesOrg": "2201", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Truck Freight / Ton" },
    "ZF11": { "salesOrg": "2212", "cXRanking": "5", "cXPriceCategory": "Fees", "Description": "Handling Flat Fee" },
    "ZF16": { "salesOrg": "2212", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Vessel Freight / Ton" },
    "ZF2": { "salesOrg": "2203", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Barge Freight / Ton" },
    "ZF22": { "salesOrg": "2212", "cXRanking": "7", "cXPriceCategory": "Misc", "Description": "Harbor Maintenance" },
    "ZF3": { "salesOrg": "2201", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Rail Freight / Ton" },
    "ZF31": { "salesOrg": "2203", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "Spread Chrg / Ton" },
    "ZF4": { "salesOrg": "2203", "cXRanking": "7", "cXPriceCategory": "Misc", "Description": "Terminal Fee / Ton" },
    "ZF6": { "salesOrg": "2201", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Misc  Freight Flat" },
    "ZF7": { "salesOrg": "2201", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Truck Fr. Flat Fee" },
    "ZF9": { "salesOrg": "2203", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Rail Fr. Flat Fee" },
    "ZLRT": { "salesOrg": "2201", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Leased Railcar/Ton" },
    "ZMF1": { "salesOrg": "BA02", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Truck Freight / Ton" },
    "ZMF2": { "salesOrg": "BE03", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Extra freight rebill" },
    "ZMF3": { "salesOrg": "CZ45", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Rail Freight / Ton" },
    "ZMF5": { "salesOrg": "BE03", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Barge Freight / Ton" },
    "ZMF6": { "salesOrg": "BE03", "cXRanking": "7", "cXPriceCategory": "Misc", "Description": "Logistics Srv / Ton" },
    "ZMF7": { "salesOrg": "BE03", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Truck Freight Flat" },
    "ZMFS": { "salesOrg": "2201", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "Misc Fuel Surcharge" },
    "ZMIS": { "salesOrg": "2212", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "Misc  Surcharge /Ton" },
    "ZPCT": { "salesOrg": "BA02", "cXRanking": "4", "cXPriceCategory": "Discount", "Description": "Disc-Pay In Adv Qty" },
    "ZPLT": { "salesOrg": "BA02", "cXRanking": "7", "cXPriceCategory": "Misc", "Description": "Pallet Charges" },
    "ZPRO": { "salesOrg": "BA02", "cXRanking": "4", "cXPriceCategory": "Discount", "Description": "Discount-Special" },
    "ZRC": { "salesOrg": "2206", "cXRanking": "6", "cXPriceCategory": "Commission", "Description": "Rockwell Commission" },
    "ZREB": { "salesOrg": "2203", "cXRanking": "4", "cXPriceCategory": "Discount", "Description": "Customer Rebates" },
    "ZRLC": { "salesOrg": "2206", "cXRanking": "6", "cXPriceCategory": "Commission", "Description": "RL Commission Basis" },
    "ZRMI": { "salesOrg": "2201", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "Fuel SurCh Rail/Mile" },
    "ZSFF": { "salesOrg": "FR95", "cXRanking": "5", "cXPriceCategory": "Fees", "Description": "Service Fee Flat" },
    "ZSFT": { "salesOrg": "RO49", "cXRanking": "5", "cXPriceCategory": "Fees", "Description": "Service Fee Quantity" },
    "ZSPA": { "salesOrg": "2210", "cXRanking": "2", "cXPriceCategory": "Freight", "Description": "Shortfall Price/Ton" },
    "ZSRM": { "salesOrg": "2201", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "Fuel SurCh Rail/MB" },
    "ZSRT": { "salesOrg": "2201", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "Fuel SurCh Rail/Ton" },
    "ZSTF": { "salesOrg": "2201", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "Fuel SurChTruck Flat" },
    "ZSTT": { "salesOrg": "2201", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "Fuel SurChTruck /Ton" },
    "ZSVF": { "salesOrg": "2212", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "FuelSurCh Vessel/Ton" },
    "ZVFS": { "salesOrg": "2201", "cXRanking": "3", "cXPriceCategory": "Surcharges", "Description": "Var F.Surch Truck" }
}
*/