export const categoryOptions = {
    "RL Commission Basis": { "fieldName": "RL_Commission_Basis__c", "category": "Commission" },
    "Rockwell Commission": { "fieldName": "Rockwell_Commission__c", "category": "Commission" },
    "WEU Commission": { "fieldName": "WEU_Commission__c", "category": "Commission" },
    "Customer Rebates": { "fieldName": "Customer_Rebates__c", "category": "Discount" },
    "Disc-Contract Qty": { "fieldName": "Disc_Contract_Qty__c", "category": "Discount" },
    "Disc-Pay In Adv %": { "fieldName": "Disc_Pay_In_Adv__c", "category": "Discount" },
    "Disc-Pay In Adv Qty": { "fieldName": "Disc_Pay_In_Adv_Qty__c", "category": "Discount" },
    "Disc-Promotion %": { "fieldName": "Disc_Promotion__c", "category": "Discount" },
    "Discount-Special": { "fieldName": "Discount_Special__c", "category": "Discount" },
    "Admin Fee / Ton": { "fieldName": "Admin_Fee_Ton__c", "category": "Fees" },
    "Admin Flat Fee": { "fieldName": "Admin_Flat_Fee__c", "category": "Fees" },
    "Handling Flat Fee": { "fieldName": "Handling_Flat_Fee__c", "category": "Fees" },
    "Service Fee Flat": { "fieldName": "Service_Fee_Flat__c", "category": "Fees" },
    "Service Fee Quantity": { "fieldName": "Service_Fee_Quantity__c", "category": "Fees" },
    "Bagged Freight": { "fieldName": "Bagged_Freight__c", "category": "Freight" },
    "Barge Freight / Ton": { "fieldName": "Barge_Freight_Ton__c", "category": "Freight" },
    "Dedicated frt rebill": { "fieldName": "Dedicated_frt_rebill__c", "category": "Freight" },
    "Extra freight rebill": { "fieldName": "Extra_freight_rebill__c", "category": "Freight" },
    "Leased Railcar/Ton": { "fieldName": "Leased_Railcar_Ton__c", "category": "Freight" },
    "Misc  Freight Flat": { "fieldName": "Misc_Freight_Flat__c", "category": "Freight" },
    "Rail Fr. Flat Fee": { "fieldName": "Rail_Fr_Flat_Fee__c", "category": "Freight" },
    "Rail Freight / Ton": { "fieldName": "Rail_Freight_Ton__c", "category": "Freight" },
    "Shortfall Price/Ton": { "fieldName": "Shortfall_Price_Ton__c", "category": "Freight" },
    "Truck Fr. Flat Fee": { "fieldName": "Truck_Fr_Flat_Fee__c", "category": "Freight" },
    "Truck Fr. Flat fee": { "fieldName": "Truck_Fr_Flat_Fee__c", "category": "Freight" },
    "Truck Freight / Ton": { "fieldName": "Truck_Freight_Ton__c", "category": "Freight" },
    "Truck Freight/Ton": { "fieldName": "Truck_Freight_Ton__c", "category": "Freight" },
    "Truck Freight Flat": { "fieldName": "Truck_Freight_Flat__c", "category": "Freight" },
    "Vessel Freight / Ton": { "fieldName": "Vessel_Freight_Ton__c", "category": "Freight" },
    "Harbor Maintenance": { "fieldName": "Harbor_Maintenance__c", "category": "Misc" },
    "Logistics Srv / Ton": { "fieldName": "Logistics_Srv_Ton__c", "category": "Misc" },
    "Pallet Charges": { "fieldName": "Pallet_Charges__c", "category": "Misc" },
    "Terminal Fee / Ton": { "fieldName": "Terminal_Fee_Ton__c", "category": "Misc" },
    "Cust material price": { "fieldName": "Cust_material_price__c", "category": "Product" },
    "Material Flat Rate": { "fieldName": "Material_Flat_Rate__c", "category": "Product" },
    "Alabama SeveranceTax": { "fieldName": "Alabama_SeveranceTax__c", "category": "Surcharges" },
    "CO2 Surcharge": { "fieldName": "CO2_Surcharge__c", "category": "Surcharges" },
    "Fuel SurCh Rail/MB": { "fieldName": "Fuel_SurCh_Rail_MB__c", "category": "Surcharges" },
    "Fuel SurCh Rail/Mile": { "fieldName": "Fuel_SurCh_Rail_Mile__c", "category": "Surcharges" },
    "Fuel SurCh Rail/Ton": { "fieldName": "Fuel_SurCh_Rail_Ton__c", "category": "Surcharges" },
    "Fuel SurChTruck /Ton": { "fieldName": "Fuel_SurChTruck_Ton__c", "category": "Surcharges" },
    "Fuel SurChTruck Flat": { "fieldName": "Fuel_SurChTruck_Flat__c", "category": "Surcharges" },
    "FuelSurCh Vessel/Ton": { "fieldName": "FuelSurCh_Vessel_Ton__c", "category": "Surcharges" },
    "Misc  Surcharge /Ton": { "fieldName": "Misc_Surcharge_Ton__c", "category": "Surcharges" },
    "Misc Fuel Surcharge": { "fieldName": "Misc_Fuel_Surcharge__c", "category": "Surcharges" },
    "Spread Chrg / Ton": { "fieldName": "Spread_Chrg_Ton__c", "category": "Surcharges" },
    "Var F.Surch Truck": { "fieldName": "Var_F_Surch_Truck__c", "category": "Surcharges" }
};